spring.application.name=Hostel-management-System
# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_db
spring.datasource.username=root
spring.datasource.password=Ishaanjain@17@

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
